# Generated by Django 2.1.5 on 2019-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('url', models.SlugField(max_length=300, unique=True, verbose_name='Ссылка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
    ]
