# Generated by Django 2.1.5 on 2019-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoryId',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID категории'),
        ),
        migrations.AddField(
            model_name='item',
            name='categoryName',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='item',
            name='groupId',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID группы'),
        ),
        migrations.AddField(
            model_name='item',
            name='id_product',
            field=models.IntegerField(blank=True, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendorName',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Производитель'),
        ),
    ]
