# Generated by Django 2.1.5 on 2019-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_auto_20190210_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Магазин'),
        ),
    ]
