# Generated by Django 2.1.5 on 2019-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0007_auto_20190217_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Магазин'),
        ),
    ]
