# Generated by Django 2.1.5 on 2019-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0013_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
