# Generated by Django 2.1.5 on 2019-02-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0016_auto_20190218_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Разница'),
        ),
    ]
