# Generated by Django 2.1.5 on 2019-02-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0017_match_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='diff',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True, verbose_name='Разница'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id_product_my',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Артикул MyShop'),
        ),
        migrations.AlterField(
            model_name='match',
            name='price_my',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, unique=True, verbose_name='Цена MyShop'),
        ),
    ]
