# Generated by Django 2.1.5 on 2019-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0018_auto_20190218_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(blank=True, null=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('categoryId', models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID категории')),
                ('categoryName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория')),
                ('vendorName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Производитель')),
                ('groupId', models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID группы')),
                ('url', models.SlugField(max_length=300, unique=True, verbose_name='Ссылка')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('shop', models.CharField(blank=True, choices=[('Мвидео', 'Мвидео'), ('Ситилинк', 'Ситилинк'), ('Wildberries', 'Wildberries')], max_length=30, null=True, verbose_name='Магазин')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'товар конкурента',
                'verbose_name_plural': 'товары конкурента',
            },
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='CompetitorProduct',
        ),
        migrations.AlterModelOptions(
            name='competitorproduct',
            options={'verbose_name': 'товар конкурента', 'verbose_name_plural': 'товары конкурента'},
        ),
    ]
