# Generated by Django 2.1.5 on 2019-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0019_auto_20190218_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproduct',
            options={'verbose_name': 'мои товар', 'verbose_name_plural': 'мои товары'},
        ),
        migrations.RemoveField(
            model_name='myproduct',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='myproduct',
            name='shop',
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='shop',
            field=models.CharField(blank=True, choices=[('М.видео', 'М.видео'), ('Ситилинк', 'Ситилинк'), ('Wildberries', 'Wildberries')], max_length=30, null=True, verbose_name='Магазин'),
        ),
    ]
