# Generated by Django 2.1.5 on 2019-02-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0020_auto_20190218_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproduct',
            options={'verbose_name': 'мой товар', 'verbose_name_plural': 'мои товары'},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='id_product_conc',
            new_name='id_product_competitor',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='name_conc',
            new_name='name_competitor',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='price_conc',
            new_name='price_competitor',
        ),
    ]
