# Generated by Django 2.1.5 on 2019-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0021_auto_20190218_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id_product_competitor',
        ),
        migrations.AddField(
            model_name='match',
            name='shop',
            field=models.CharField(blank=True, choices=[('М.видео', 'М.видео'), ('Ситилинк', 'Ситилинк'), ('Wildberries', 'Wildberries')], max_length=30, null=True, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id_product_my',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name_my',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Мое имя'),
        ),
        migrations.AlterField(
            model_name='match',
            name='price_my',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, unique=True, verbose_name='Моя цена'),
        ),
    ]
