# Generated by Django 2.1.5 on 2019-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0023_auto_20190218_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name_competitor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Товар конкурента'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name_my',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Мой товар'),
        ),
        migrations.AlterField(
            model_name='match',
            name='shop_competitor',
            field=models.CharField(blank=True, choices=[('М.видео', 'М.видео'), ('Ситилинк', 'Ситилинк'), ('Wildberries', 'Wildberries')], max_length=30, null=True, verbose_name='Конкурент'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
    ]
