# Generated by Django 2.1.5 on 2019-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0027_match_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='price_my',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Моя цена'),
        ),
    ]
