# Generated by Django 2.1.5 on 2019-02-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0028_auto_20190219_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name_my',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Товар'),
        ),
    ]
