# Generated by Django 2.1.5 on 2019-02-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0030_match_headshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='headshot',
            new_name='image',
        ),
    ]
