# Generated by Django 2.1.5 on 2019-02-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0031_auto_20190220_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='image',
        ),
    ]
