# Generated by Django 2.1.5 on 2019-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0033_auto_20190222_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='При добавлении нового сравнения вручную дата добавляется <em>автоматически</em>.', null=True, verbose_name='Дата сравнения'),
        ),
        migrations.AlterField(
            model_name='match',
            name='name_my',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Товар'),
        ),
    ]
